name: 🛠️ Setup
description: Set up Node.js and install dependencies.
runs:
  using: composite
  steps:
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: 📥 Install dependencies
      shell: bash
      run: npm install
